version: "3"

volumes:
  data:

services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
      - data:/var/lib/postgres/data
